"use client";
import React, { useState, useEffect, useCallback, useMemo } from "react";
import { useCase } from "@/context/CaseContext";

export default function AnalyticsPage() {
  const { activeCaseId, activeCase } = useCase();
  const [metrics, setMetrics] = useState<any>(null);
  const [entities, setEntities] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [centralityTab, setCentralityTab] = useState<"pagerank" | "betweenness" | "closeness" | "degree">("pagerank");

  const getApiUrl = (path: string) => {
    const baseUrl = process.env.NEXT_PUBLIC_API_URL || "";
    return `${baseUrl}${path}`;
  };

  const fetchAnalytics = useCallback(async () => {
    if (!activeCaseId) {
      setMetrics(null);
      setEntities([]);
      setLoading(false);
      return;
    }
    const token = localStorage.getItem("token");
    try {
      setLoading(true);
      // Fetch Entities for profile names mapping
      const entRes = await fetch(getApiUrl(`/api/entities/?case_id=${activeCaseId}`), {
        headers: { Authorization: `Bearer ${token}` }
      });
      let entsList: any[] = [];
      if (entRes.ok) {
        entsList = await entRes.json();
        setEntities(entsList);
      }

      // Fetch Network metrics
      const res = await fetch(getApiUrl(`/api/analytics/${activeCaseId}`), {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setMetrics(data);
      }
    } catch (err) {
      console.error("Failed to load analytics:", err);
    } finally {
      setLoading(false);
    }
  }, [activeCaseId]);

  useEffect(() => {
    fetchAnalytics();
  }, [fetchAnalytics]);

  // Map node centralities to actual names and sort them
  const rankedEntities = useMemo(() => {
    if (!metrics || entities.length === 0) return [];
    
    let centData: Record<string, number> = {};
    if (centralityTab === "pagerank") centData = metrics.pagerank || {};
    else if (centralityTab === "betweenness") centData = metrics.betweenness_centrality || {};
    else if (centralityTab === "closeness") centData = metrics.closeness_centrality || {};
    else centData = metrics.degree_centrality || {};

    return Object.entries(centData)
      .map(([nodeId, score]) => {
        const ent = entities.find(e => e._id === nodeId);
        return {
          id: nodeId,
          name: ent ? ent.name : `ID: ${nodeId.slice(0, 6)}...`,
          type: ent ? ent.type : "Unknown",
          risk: ent ? ent.risk_score : 0.0,
          score: score
        };
      })
      .sort((a, b) => b.score - a.score);
  }, [metrics, entities, centralityTab]);

  // Group detected Louvain communities by member profiles
  const communitiesList = useMemo(() => {
    if (!metrics || !metrics.communities || entities.length === 0) return [];

    return metrics.communities.map((comm: string[], idx: number) => {
      const members = comm.map(nodeId => {
        const ent = entities.find(e => e._id === nodeId);
        return {
          id: nodeId,
          name: ent ? ent.name : `ID: ${nodeId.slice(0, 6)}...`,
          risk: ent ? ent.risk_score : 0.0,
          type: ent ? ent.type : "Unknown"
        };
      });

      const avgRisk = members.reduce((sum, m) => sum + m.risk, 0) / (members.length || 1);

      return {
        id: idx + 1,
        members: members,
        avgRisk: avgRisk
      };
    }).sort((a: any, b: any) => b.avgRisk - a.avgRisk); // sort by highest average risk community first
  }, [metrics, entities]);

  return (
    <div className="flex flex-col gap-8 max-w-7xl mx-auto w-full">
      {/* Header */}
      <div className="border-b border-white/5 pb-5">
        <h1 className="text-2xl font-extrabold tracking-tight">Case Network Analytics</h1>
        <p className="text-sm text-zinc-500 mt-1">
          Algorithmic network structure evaluation. Centralities and community clusters generated by NetworkX.
        </p>
      </div>

      {!activeCaseId ? (
        <div className="p-16 border border-dashed border-white/5 rounded-2xl text-center text-zinc-600">
          Please select an active Case File from the sidebar to inspect case analytics.
        </div>
      ) : loading ? (
        <div className="p-16 flex flex-col items-center justify-center gap-3">
          <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-blue-500"></div>
          <span className="text-xs text-zinc-500">Running graph centrality evaluations...</span>
        </div>
      ) : !metrics ? (
        <div className="p-16 border border-dashed border-white/5 rounded-2xl text-center text-zinc-600">
          No analytics data could be parsed. Ingest evidence files to populate case network data.
        </div>
      ) : (
        <>
          {/* Top Level Metrics Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="bg-zinc-900/30 border border-white/5 p-6 rounded-2xl">
              <span className="text-zinc-500 text-xs font-bold uppercase tracking-wider block mb-1">Total Suspect Nodes</span>
              <p className="text-3xl font-extrabold text-white">{metrics.nodes}</p>
            </div>
            <div className="bg-zinc-900/30 border border-white/5 p-6 rounded-2xl">
              <span className="text-zinc-500 text-xs font-bold uppercase tracking-wider block mb-1">Relationship Links</span>
              <p className="text-3xl font-extrabold text-white">{metrics.edges}</p>
            </div>
            <div className="bg-zinc-900/30 border border-white/5 p-6 rounded-2xl">
              <span className="text-zinc-500 text-xs font-bold uppercase tracking-wider block mb-1">Network Density</span>
              <p className="text-3xl font-extrabold text-blue-400">{(metrics.density || 0.0).toFixed(4)}</p>
            </div>
            <div className="bg-zinc-900/30 border border-white/5 p-6 rounded-2xl">
              <span className="text-zinc-500 text-xs font-bold uppercase tracking-wider block mb-1">Detected Communities</span>
              <p className="text-3xl font-extrabold text-emerald-400">{communitiesList.length}</p>
            </div>
          </div>

          {/* Grid split: Left is Centrality ranking list, Right is Community clusters list */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            
            {/* Left Box: Centrality Rankings */}
            <div className="bg-zinc-900/20 border border-white/5 p-6 rounded-2xl flex flex-col min-h-[400px]">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-lg font-bold text-zinc-300">👑 Centrality Rankings</h2>
                
                {/* Centrality selectors */}
                <div className="flex gap-1.5 p-1 bg-zinc-950 border border-white/10 rounded-lg text-[10px] font-bold uppercase font-mono">
                  <button 
                    onClick={() => setCentralityTab("pagerank")}
                    className={`px-2 py-1 rounded transition-colors ${centralityTab === "pagerank" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-white"}`}
                  >
                    PageRank
                  </button>
                  <button 
                    onClick={() => setCentralityTab("betweenness")}
                    className={`px-2 py-1 rounded transition-colors ${centralityTab === "betweenness" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-white"}`}
                  >
                    Betweenness
                  </button>
                  <button 
                    onClick={() => setCentralityTab("closeness")}
                    className={`px-2 py-1 rounded transition-colors ${centralityTab === "closeness" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-white"}`}
                  >
                    Closeness
                  </button>
                  <button 
                    onClick={() => setCentralityTab("degree")}
                    className={`px-2 py-1 rounded transition-colors ${centralityTab === "degree" ? "bg-blue-600 text-white" : "text-zinc-400 hover:text-white"}`}
                  >
                    Degree
                  </button>
                </div>
              </div>

              {rankedEntities.length === 0 ? (
                <div className="flex-grow flex items-center justify-center text-zinc-600 text-xs italic">No centrality rankings computed.</div>
              ) : (
                <div className="overflow-y-auto max-h-[480px] space-y-2 pr-1">
                  {rankedEntities.map((ent, idx) => (
                    <div key={ent.id} className="p-3.5 bg-zinc-950/60 border border-white/5 rounded-xl flex items-center justify-between text-xs">
                      <div className="flex items-center gap-3">
                        <span className="font-mono text-zinc-600 font-extrabold w-5">#{idx + 1}</span>
                        <div>
                          <p className="font-bold text-white text-sm">{ent.name}</p>
                          <p className="text-[10px] text-zinc-500 font-semibold uppercase">{ent.type}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="font-bold font-mono text-blue-400">{ent.score.toFixed(4)}</p>
                        <p className="text-[10px] text-zinc-500">Risk index: {ent.risk.toFixed(1)}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Right Box: Louvain Community Clusters */}
            <div className="bg-zinc-900/20 border border-white/5 p-6 rounded-2xl flex flex-col min-h-[400px]">
              <h2 className="text-lg font-bold text-zinc-300 mb-6">🔍 Community Clusters (Louvain)</h2>
              
              {communitiesList.length === 0 ? (
                <div className="flex-grow flex items-center justify-center text-zinc-600 text-xs italic">No clusters detected.</div>
              ) : (
                <div className="overflow-y-auto max-h-[480px] space-y-4 pr-1">
                  {communitiesList.map((comm: any) => (
                    <div key={comm.id} className="p-4 bg-zinc-950/60 border border-white/5 rounded-xl space-y-3">
                      <div className="flex justify-between items-center border-b border-white/5 pb-2">
                        <span className="font-bold text-sm text-zinc-300">Cluster Group #{comm.id}</span>
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                          comm.avgRisk > 0.7 
                            ? "bg-red-500/10 border-red-500/15 text-red-400 font-extrabold" 
                            : comm.avgRisk > 0.4 
                            ? "bg-yellow-500/10 border-yellow-500/15 text-yellow-400"
                            : "bg-blue-500/10 border-blue-500/15 text-blue-400"
                        }`}>
                          Avg Risk: {comm.avgRisk.toFixed(2)}
                        </span>
                      </div>
                      
                      <div className="flex flex-wrap gap-2">
                        {comm.members.map((m: any) => (
                          <div 
                            key={m.id}
                            className="px-2.5 py-1.5 rounded-lg bg-zinc-900 border border-white/5 text-[11px] text-zinc-400 flex items-center gap-1.5"
                          >
                            <span className={`h-1.5 w-1.5 rounded-full ${
                              m.risk > 0.7 ? "bg-red-500" : m.risk > 0.4 ? "bg-yellow-500" : "bg-blue-500"
                            }`} />
                            <span className="text-white font-bold">{m.name}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

          </div>
        </>
      )}
    </div>
  );
}
